#!/usr/bin/env python3
"""Generate the IA2 on-disk artifacts from ia2_config.json.

`ia2_config.json` is the single contract for the register map. IA2 stays in
lockstep with it via generated files:

  * `ia2_project/devices/<device>.toml`  — ONE Modbus device per slave (the rig
                                           is multi-slave behind an RTU-to-TCP
                                           gateway; each slave_id is its own IA2
                                           device pointing at the same TCP port).
  * `ia2_project/iomap.toml`             — variable <-> channel bindings, each
                                           referencing the per-slave device.

This script regenerates them from the contract, so adding a register becomes an
edit to ia2_config.json + a regen. It also VALIDATES that pous/threetank.st
declares a variable for every contract register (the ST body is hand-written;
only the names must match).

Usage:
    python3 tools/gen_ia2_artifacts.py          # regenerate devices + iomap
    python3 tools/gen_ia2_artifacts.py --check  # CI: exit 1 on drift, no writes
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONFIG = ROOT / "ia2_config.json"
DEVICES_DIR = ROOT / "ia2_project" / "devices"
IOMAP_TOML = ROOT / "ia2_project" / "iomap.toml"
ST_POU = ROOT / "ia2_project" / "pous" / "threetank.st"

# ia2_config "type" -> IA2 channel data_type.
TYPE_MAP = {
    "uint16": "u16", "int16": "i16", "uint32": "u32", "int32": "i32",
    "float": "f32", "float32": "f32", "f32": "f32",   # 32-bit float -> 2 regs
    "bool": "bool",
}
# ia2_config "table" -> IA2 channel kind (the Modbus function-code family).
TABLE_TO_KIND = {
    "holding": "holding_register",        # FC03 read / FC06,FC16 write
    "input": "input_register",            # FC04 read
    "discrete_input": "discrete_input",   # FC02 read
    "coil": "coil",                       # FC01 read / FC05,FC15 write
}
# 32-bit data types that span two registers and take a word_order field.
_WIDE = {"f32", "u32", "i32"}
# contract word_order -> IA2 word_order token.
WORD_ORDER_MAP = {"big": "hi_lo", "little": "lo_hi"}   # hi_lo = ABCD (Modbus default)

INSTANCE = "threetank_inst"   # C15: iomap application = instance name, not POU name


def load_config() -> dict:
    with open(CONFIG) as fh:
        return json.load(fh)


def _kind_for(r: dict) -> str:
    return TABLE_TO_KIND.get(r.get("table", "holding"), "holding_register")


def _data_type_for(r: dict) -> str:
    return TYPE_MAP.get(r["type"], r["type"])


def _device_name_for_slave(cfg: dict, slave_id: int) -> str:
    """cabinet_<role> from the contract `slaves` map (e.g. cabinet_ai for slave 2)."""
    for role, info in cfg.get("slaves", {}).items():
        if int(info["slave_id"]) == int(slave_id):
            return f"cabinet_{role}"
    return f"cabinet_slave{slave_id}"


def _channel_block(r: dict) -> list[str]:
    """One IA2 [[channels]] block for a contract register."""
    dt = _data_type_for(r)
    lines = [
        "[[channels]]",
        f"name = \"{r['name']}\"",
        f"kind = \"{_kind_for(r)}\"",
        f"address = {r['address']}",
        f"data_type = \"{dt}\"",
    ]
    if dt in _WIDE:
        wo = WORD_ORDER_MAP.get(r.get("word_order", "big"), "hi_lo")
        lines.append(f"word_order = \"{wo}\"")
    return lines


def gen_devices(cfg: dict) -> dict[str, str]:
    """One device TOML per slave_id -> {device_name: toml_text}."""
    m = cfg["modbus"]
    poll = cfg.get("timing", {}).get("modbus_poll_ms", 50)
    host, port = m["host"], int(m["port"])
    by_slave: dict[int, list[dict]] = {}
    for r in cfg["registers"]:
        by_slave.setdefault(int(r["slave_id"]), []).append(r)

    out: dict[str, str] = {}
    for slave_id in sorted(by_slave):
        dev = _device_name_for_slave(cfg, slave_id)
        regs = sorted(by_slave[slave_id], key=lambda r: r["address"])
        lines = [
            "# AUTO-GENERATED by tools/gen_ia2_artifacts.py — edit ia2_config.json, not this file.",
            f"# Modbus TCP device for slave {slave_id} ({len(regs)} channel(s)) behind the RTU-to-TCP gateway.",
            "# 32-bit data types (f32/u32/i32) span two consecutive registers from `address`.",
            "",
            f"name = \"{dev}\"",
            "protocol = \"modbus\"",
            f"slave_id = {slave_id}",
            f"poll_interval_ms = {poll}",
            "",
            "[transport]",
            "kind = \"tcp\"",
            f"host = \"{host}\"",
            f"port = {port}",
            "",
        ]
        for r in regs:
            lines += _channel_block(r)
        out[dev] = "\n".join(lines) + "\n"
    return out


def gen_iomap_toml(cfg: dict) -> str:
    """Bind every contract register to its POU var on the right per-slave device."""
    regs = cfg["registers"]
    inputs = [r for r in regs if r["direction"] == "read"]
    outputs = sorted([r for r in regs if r["direction"] == "write"],
                     key=lambda r: (r["name"] == "reset_cmd", r["address"]))  # reset last

    def mappings(title: str, rs: list[dict], direction: str) -> list[str]:
        lines = [f"# --- {title} ---"]
        for r in rs:
            dev = _device_name_for_slave(cfg, int(r["slave_id"]))
            lines += [
                "[[mappings]]",
                f"application = \"{INSTANCE}\"",
                f"variable = \"{r['name']}\"",
                f"direction = \"{direction}\"",
                f"device = \"{dev}\"",
                f"channel = \"{r['name']}\"",
            ]
        return lines

    out = [
        "# AUTO-GENERATED by tools/gen_ia2_artifacts.py — edit ia2_config.json, not this file.",
        f"# Binds PROGRAM ThreeTank variables to per-slave device channels.",
        "# direction: input = channel -> POU,  output = POU -> channel.",
        "# Source of truth: ia2_config.json.",
        "",
    ]
    out += mappings("sensors: cabinet input/discrete channels -> POU variables", inputs, "input")
    out.append("")
    out += mappings("actuators + reset: POU variables -> cabinet holding channels", outputs, "output")
    return "\n".join(out) + "\n"


def declared_st_vars() -> set[str]:
    """Names declared in any VAR..END_VAR block of threetank.st.

    ST permits several declarations on one line (`a : REAL; b : REAL;`), so scan
    the whole block for `IDENT :` (negative lookahead on `=` to skip `:=`).
    """
    text = ST_POU.read_text()
    names: set[str] = set()
    for block in re.finditer(r"\bVAR\b(.*?)\bEND_VAR\b", text, re.S | re.IGNORECASE):
        for m in re.finditer(r"([A-Za-z_]\w*)\s*:(?!=)", block.group(1)):
            names.add(m.group(1))
    return names


def validate_st(cfg: dict) -> list[str]:
    """Return contract register names missing from the ST VAR declarations."""
    declared = declared_st_vars()
    return [r["name"] for r in cfg["registers"] if r["name"] not in declared]


def write_if_changed(path: Path, content: str) -> bool:
    if path.exists() and path.read_text() == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    return True


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="verify up-to-date; no writes; exit 1 on drift")
    args = ap.parse_args()

    cfg = load_config()
    devices = gen_devices(cfg)
    iomap_txt = gen_iomap_toml(cfg)

    missing = validate_st(cfg)
    if missing:
        print(f"FAIL: threetank.st is missing VAR declarations for: {', '.join(missing)}",
              file=sys.stderr)
        st_fail = True
    else:
        print("ST VAR names OK: every contract register is declared in threetank.st.")
        st_fail = False

    # device files this contract should produce (for stale-file detection)
    expected_device_files = {f"{d}.toml" for d in devices}

    drift = []
    # iomap
    rel = IOMAP_TOML.relative_to(ROOT)
    if (IOMAP_TOML.read_text() if IOMAP_TOML.exists() else None) != iomap_txt:
        drift.append(str(rel))
        if not args.check:
            IOMAP_TOML.write_text(iomap_txt)
            print(f"  wrote {rel}")
        else:
            print(f"  DRIFT: {rel}")
    # device files
    for dev, content in devices.items():
        path = DEVICES_DIR / f"{dev}.toml"
        rel = path.relative_to(ROOT)
        if (path.read_text() if path.exists() else None) != content:
            drift.append(str(rel))
            if not args.check:
                path.write_text(content)
                print(f"  wrote {rel}")
            else:
                print(f"  DRIFT: {rel}")
    # stale device files (e.g. the legacy single-device mock_cabinet.toml)
    if DEVICES_DIR.exists():
        for stale in DEVICES_DIR.glob("*.toml"):
            if stale.name not in expected_device_files:
                rel = stale.relative_to(ROOT)
                drift.append(f"{rel} (stale)")
                if not args.check:
                    stale.unlink()
                    print(f"  removed stale {rel}")
                else:
                    print(f"  DRIFT (stale): {rel}")

    if args.check:
        if drift:
            print(f"\nFAIL: {len(drift)} file(s) out of date — run: python3 tools/gen_ia2_artifacts.py",
                  file=sys.stderr)
            return 1
        if st_fail:
            print("\nFAIL: ST VAR validation failed (see above).", file=sys.stderr)
            return 1
        print("\nOK: generated artifacts match the contract + ST vars validated.")
        return 0
    if not drift:
        print("OK: all artifacts already up to date.")
    else:
        print(f"\nRegenerated {len(drift)} file(s) from ia2_config.json.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
