#!/usr/bin/env python3
"""Generate the IA2 on-disk artifacts from ia2_config.json.

`ia2_config.json` is the single contract for the register map. Two IA2 files
must stay in lockstep with it, and currently are hand-duplicated:

  * `ia2_project/devices/mock_cabinet.toml`  — the Modbus TCP device + channels
  * `ia2_project/iomap.toml`                 — variable <-> channel bindings

This script regenerates both from the contract, so adding a register (reset,
heaters, ...) becomes an edit to `ia2_config.json` + a regen instead of four
hand-synced files. It also VALIDATES that `pous/threetank.st` declares a
variable for every contract register (the ST *body* is hand-written and will
become the safety layer; only the names must match).

The `req`/`mapped` split (PLC safety layer) is intentionally NOT baked in — when
it lands, it becomes a config-schema extension this same generator consumes.

Usage:
    python3 tools/gen_ia2_artifacts.py          # regenerate the two TOMLs
    python3 tools/gen_ia2_artifacts.py --check  # CI: exit 1 on drift, no writes
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONFIG = ROOT / "ia2_config.json"
DEVICE_TOML = ROOT / "ia2_project" / "devices" / "mock_cabinet.toml"
IOMAP_TOML = ROOT / "ia2_project" / "iomap.toml"
ST_POU = ROOT / "ia2_project" / "pous" / "threetank.st"

# ia2_config "type" -> IA2 device-channel data_type
TYPE_MAP = {"uint16": "u16", "int16": "i16", "uint32": "u32", "int32": "i32"}


def load_config() -> dict:
    with open(CONFIG) as fh:
        return json.load(fh)


def gen_device_toml(cfg: dict) -> str:
    m = cfg["modbus"]
    regs = cfg["registers"]
    dev = cfg["ia2"]["device_name"]
    out = [
        "# AUTO-GENERATED by tools/gen_ia2_artifacts.py — edit ia2_config.json, not this file.",
        f"# Regenerate: python3 tools/gen_ia2_artifacts.py   (CI: --check)",
        "#",
        f"# Modbus TCP device for the {len(regs)}-register mock cabinet. `address` is the 0-based",
        "# protocol register address (= PLC 4xxxx - 40001). Scale/units live in ia2_config.json.",
        "# Legacy top-level {host, port} shape — IA2 auto-upgrades it to transport.kind=tcp.",
        "",
        f"name = \"{dev}\"",
        "protocol = \"modbus\"",
        f"host = \"{m['host']}\"",
        f"port = {m['port']}",
        f"slave_id = {m['unit_id']}",
        f"poll_interval_ms = {m.get('poll_interval_ms', 50)}",
        "",
    ]
    for r in regs:
        out += [
            "[[channels]]",
            f"name = \"{r['name']}\"",
            "kind = \"holding_register\"",
            f"address = {r['address']}",
            f"data_type = \"{TYPE_MAP.get(r['type'], r['type'])}\"",
        ]
    return "\n".join(out) + "\n"


def gen_iomap_toml(cfg: dict) -> str:
    pou = cfg["ia2"]["application_pou"]
    dev = cfg["ia2"]["device_name"]
    regs = cfg["registers"]
    inputs = [r for r in regs if r["direction"] == "read"]
    outputs = [r for r in regs if r["direction"] == "write"]

    def mappings(title: str, rs: list[dict], direction: str) -> list[str]:
        lines = [f"# --- {title} ---"]
        for r in rs:
            lines += [
                "[[mappings]]",
                f"application = \"{pou}\"",
                f"variable = \"{r['name']}\"",
                f"direction = \"{direction}\"",
                f"device = \"{dev}\"",
                f"channel = \"{r['name']}\"",
            ]
        return lines

    out = [
        "# AUTO-GENERATED by tools/gen_ia2_artifacts.py — edit ia2_config.json, not this file.",
        f"# Binds PROGRAM {pou} variables to {dev} channels.",
        "# direction: input = cabinet -> POU,  output = POU -> cabinet.",
        "# Source of truth: ia2_config.json.",
        "",
    ]
    out += mappings("sensors: cabinet holding registers -> POU variables", inputs, "input")
    out.append("")
    out += mappings("actuators: POU variables -> cabinet holding registers", outputs, "output")
    return "\n".join(out) + "\n"


def declared_st_vars() -> set[str]:
    """Names declared in any VAR..END_VAR block of threetank.st."""
    text = ST_POU.read_text()
    names: set[str] = set()
    for block in re.finditer(r"\bVAR\b(.*?)\bEND_VAR\b", text, re.S | re.IGNORECASE):
        for line in block.group(1).splitlines():
            m = re.match(r"\s*([A-Za-z_]\w*)\s*:", line)
            if m:
                names.add(m.group(1))
    return names


def validate_st(cfg: dict) -> list[str]:
    """Return contract register names missing from the ST VAR declarations."""
    declared = declared_st_vars()
    return [r["name"] for r in cfg["registers"] if r["name"] not in declared]


def write_if_changed(path: Path, content: str) -> bool:
    """Write only on change; return True if the file was (re)written."""
    if path.exists() and path.read_text() == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    return True


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="verify up-to-date; no writes; exit 1 on drift")
    args = ap.parse_args()

    cfg = load_config()
    device_txt = gen_device_toml(cfg)
    iomap_txt = gen_iomap_toml(cfg)

    # ST name check (advisory in --check mode, always reported).
    missing = validate_st(cfg)
    if missing:
        print(f"WARNING: threetank.st is missing VAR declarations for: {', '.join(missing)}", file=sys.stderr)
    else:
        print("ST VAR names OK: every contract register is declared in threetank.st.")

    drift = []
    for path, content in ((DEVICE_TOML, device_txt), (IOMAP_TOML, iomap_txt)):
        rel = path.relative_to(ROOT)
        current = path.read_text() if path.exists() else None
        if current != content:
            drift.append(str(rel))
            if not args.check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content)
                print(f"  wrote {rel}")
            else:
                print(f"  DRIFT: {rel}")

    if args.check:
        if drift:
            print(f"\nFAIL: {len(drift)} file(s) out of date — run: python3 tools/gen_ia2_artifacts.py", file=sys.stderr)
            return 1
        print("\nOK: generated artifacts match the contract.")
        return 0
    if not drift:
        print("OK: all artifacts already up to date.")
    else:
        print(f"\nRegenerated {len(drift)} file(s) from ia2_config.json.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
